### ISSUE TITLE
Localização das imagens

### ISSUE THREAD

**Issue by mkyy** [celso-henrique/naruto-quotes-client#1]
Comumente eu vejo as imagens de um projeto salvas em uma pasta chamada 'assets', dentro da pasta 'public'.

Nesse projeto você deixou dentro de uma pasta 'images' no 'src'.

Muda alguma coisa ? É de preferencia do desenvolvedor decidir isso ou tem algum padrão que nos diz o que é desejavel ?

**Comment by celso-henrique** [comment]
fica a critério da pessoa desenvolvedora
